services:
  - type: web
    name: portfolio-relay
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    envVars:
      - key: RELAY_API_KEY
        value: will-portfolio-2026
      - key: WA_PHONE
        value: "16282935371"
      - key: WA_APIKEY
        value: "8937649"
